# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15registry_server.proto\x1a\x1bgoogle/protobuf/empty.proto\"L\n\x12Server_information\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04\x61\x64\x64r\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x07\n\x05_nameB\x07\n\x05_addr\"\'\n\x07Success\x12\x12\n\x05value\x18\x01 \x01(\x08H\x00\x88\x01\x01\x42\x08\n\x06_value\"3\n\x0bServer_book\x12$\n\x07servers\x18\x01 \x03(\x0b\x32\x13.Server_information2r\n\x08Maintain\x12/\n\x0eRegisterServer\x12\x13.Server_information\x1a\x08.Success\x12\x35\n\rGetServerList\x12\x16.google.protobuf.Empty\x1a\x0c.Server_bookb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVER_INFORMATION._serialized_start=54
  _SERVER_INFORMATION._serialized_end=130
  _SUCCESS._serialized_start=132
  _SUCCESS._serialized_end=171
  _SERVER_BOOK._serialized_start=173
  _SERVER_BOOK._serialized_end=224
  _MAINTAIN._serialized_start=226
  _MAINTAIN._serialized_end=340
# @@protoc_insertion_point(module_scope)
